id: I94874199
ocr_import_info:
  timestamp: '2023-08-17T01:57:40.312390+00:00'
  batch_id: batch-b92c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-17 04:35:13.721201+00:00
last_modified: 2023-08-17 04:35:13.721209+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W11249
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW11249
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བསོད་ནམས་སེངྒེ
  languages:
  - bo
  author: ངོར་མཁན་ཆེན ༠༦་བསོད་ནམས་སེངྒེ
statistics:
  ocr_word_mean_confidence_index: 0.9566429571927638
  ocr_word_median_confidence_index: 0.99529856
bases:
  I0436:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0436
      total_pages: 647
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I0436.txt
    statistics:
      ocr_word_median_confidence_index: 0.996295515
      ocr_word_mean_confidence_index: 0.9617163911073109
  I0432:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0432
      total_pages: 689
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0432.txt
    statistics:
      ocr_word_median_confidence_index: 0.9939605
      ocr_word_mean_confidence_index: 0.9541913925332475
  I0433:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0433
      total_pages: 675
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0433.txt
    statistics:
      ocr_word_median_confidence_index: 0.9923480499999999
      ocr_word_mean_confidence_index: 0.9530483232335448
  I0435:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0435
      total_pages: 759
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I0435.txt
    statistics:
      ocr_word_median_confidence_index: 0.9974265
      ocr_word_mean_confidence_index: 0.9637567093764515
  I0431:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0431
      total_pages: 797
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0431.txt
    statistics:
      ocr_word_median_confidence_index: 0.9949373
      ocr_word_mean_confidence_index: 0.9566290851653183
  I0440:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0440
      total_pages: 706
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I0440.txt
    statistics:
      ocr_word_median_confidence_index: 0.9982260350000001
      ocr_word_mean_confidence_index: 0.9636059621287208
  I0439:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0439
      total_pages: 729
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I0439.txt
    statistics:
      ocr_word_median_confidence_index: 0.9929444
      ocr_word_mean_confidence_index: 0.9509889925088063
  I0434:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0434
      total_pages: 763
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0434.txt
    statistics:
      ocr_word_median_confidence_index: 0.99583937
      ocr_word_mean_confidence_index: 0.9594930226190066
  I0441:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0441
      total_pages: 586
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I0441.txt
    statistics:
      ocr_word_median_confidence_index: 0.989298075
      ocr_word_mean_confidence_index: 0.9416784352964901
  I0442:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0442
      total_pages: 703
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I0442.txt
    statistics:
      ocr_word_median_confidence_index: 0.99495614
      ocr_word_mean_confidence_index: 0.9540978860268671
  I0438:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0438
      total_pages: 482
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I0438.txt
    statistics:
      ocr_word_median_confidence_index: 0.9918233
      ocr_word_mean_confidence_index: 0.9512516398169302
  I0437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0437
      total_pages: 609
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I0437.txt
    statistics:
      ocr_word_median_confidence_index: 0.99748397
      ocr_word_mean_confidence_index: 0.9642301882212462
  I0443:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0443
      total_pages: 705
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I0443.txt
    statistics:
      ocr_word_median_confidence_index: 0.99581
      ocr_word_mean_confidence_index: 0.955890753443628
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
